services:
  postgres-product:
    image: 'postgres:latest'
    container_name: postgres-product
    environment:
      - 'POSTGRES_DB=products_db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=admin'
    volumes:
      - products_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d products_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  #    networks:
  #      - devsecops-project-net

  postgres-command:
    image: 'postgres:latest'
    container_name: postgres-command
    environment:
      - 'POSTGRES_DB=commands_db'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=admin'
    volumes:
      - commands_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d commands_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  #    networks:
  #      - devsecops-project-net

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.4
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  products_data:
  commands_data:
  pgadmin_data:
  keycloak_data:


